title: Computational Plasma Physics Knowledge Base
logo: media/images/DLOGO.png
description: This is a computational physics knowledge base for research at Dartmouth College's Department of Physics and Astronomy.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
